
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.rubber.admin.**.entity
  global-config:
    db-config:
      id-type: AUTO
      field-strategy: NOT_NULL
      table-underline: true

# Shiro
shiro:
  # 登录地址
  loginUrl: /login
  logOutUrl: /logout
  # 权限认证失败地址
  unauthorizedUrl: /auth-error
  # 首页地址
  successUrl: /index
  # 验证码开关
  anonUrl: true
  enableRedisCache: true

  sessionTimeOut: 2

  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain:
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30




spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/rubber-admin?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    logSlowSql: true
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000


  redis:
    cluster:
      nodes: 127.0.0.1:7000,127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005
      connectionTimeout: 6000
      soTimeout: 6000
      maxAttempts: 5
      password: 123456
    password: 123456
    jedis:
      pool:
        max-active: 600
        max-idle: 300
server:
  port: 8081